baseURL = "https://supports.uptime-formation.fr/"
languageCode = "fr-FR"
title = "Formations Uptime"
theme = ["hugo-theme-learn", "reveal-hugo"]

# Pour la fonctionnalit√© de recherche
[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
editURL = "https://github.com/Uptime-Formation/hugo_supports"
globalTitle = "Cursus DevOps - 2021"

[params.reveal_hugo]
custom_theme = "reveal-hugo/themes/robot-lung.css"

# [menu.shortcuts]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true